spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     # it will be none later(flyway)
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:change-me-please-at-least-32-chars}